// AUTO-GENERATED by sync_dashboard.py — do not edit manually.
window.WORKSPACE_DATA = {
  updated: "2026-08-26 02:04",
  owner: "Shiblu (Atiquzzaman)",
  sections: {
    command_center: {
      title: 'Command Center',
      icon: '🎛️',
      desc: 'Hermes Agent এর সাথে চ্যাট লগ ও অ্যাকটিভ টাস্ক',
      items: [
        {text: 'Opera autolaunch বন্ধ করা হয়েছে (registry থেকে সরানো)', date: '2026-08-19'},
        {text: 'Microsoft Edge autolaunch বন্ধ করা হয়েছে', date: '2026-08-19'},
        {text: 'ফোল্ডার স্ট্রাকচার (01-07) তৈরি', date: '2026-08-19'},
        {text: 'HTML ড্যাশবোর্ড + data.js', date: '2026-08-19'},
        {text: '৫টা ক্রনজব: Daily Briefing, Reminder Checker, Weekly Review, Weekly Backup, Weekly Research', date: '2026-08-19'},
        {text: 'রিমাইন্ডার সিস্টেম টেস্ট সফল', date: '2026-08-19'},
        {text: 'ইম্প্রুভমেন্ট: সেশন ডাটা, কুইক-কমান্ড, সার্চ, ফিল্টার, স্ট্যাটাস বার, ভয়েস ব্রিফিং, হ্যাবিট/ফিনান্স/মুড ট্র্যাকার, মোবাইল অনলাইন, গুগল হেল্পার', date: '2026-08-19'},
      ]
    },
    calendar: {
      title: 'Calendar',
      icon: '📅',
      desc: 'মিটিং, অ্যাপয়েন্টমেন্ট ও রিমাইন্ডার',
      items: [
        {text: 'Upay Sponsor Meeting ✅ Done', date: '2026-08-23'},
      ]
    },
    book_notes: {
      title: 'Book Notes',
      icon: '📚',
      desc: 'পড়া বইয়ের নোট ও সামারি',
      items: [
      ]
    },
    memory_world: {
      title: 'Memory World',
      icon: '🧠',
      desc: 'দৈনন্দিন জার্নাল ও লং-টার্ম মেমোরি',
      items: [
        {text: 'ডেইলি লাইফ অটোমেট করার সিদ্ধান্ত', date: '2026-08-19'},
      ]
    },
    research: {
      title: 'Research',
      icon: '🔬',
      desc: 'ইউটিউব স্ক্রিপ্ট, বিজনেস আইডিয়া, কম্পিটিটর রিসার্চ',
      items: [
      ]
    },
    lead_pipeline: {
      title: 'Lead Pipeline',
      icon: '🎯',
      desc: 'ক্লায়েন্ট/কাস্টমার ট্র্যাকিং (Prospect → Client)',
      items: [
      ]
    },
    batch_day_52: {
      title: 'Batch Day 52',
      icon: '🎓',
      desc: 'ব্যাচ প্রোগ্রাম হাব — মেম্বার, শিডিউল, ডক, ইভেন্ট',
      items: [
        {text: '[YYYY-MM-DD] — [ইভেন্ট/ক্লাস]', date: 'Batch'},
        {text: 'আসন্ন', date: 'Batch'},
      ]
    },
    sponsors: {
      title: 'Sponsors & Partners',
      icon: '🤝',
      desc: 'স্পন্সর, প্রপোজাল, মিটিং ট্র্যাকিং',
      items: [
        {text: '[কোম্পানি/ব্র্যান্ড নাম] (Lead)', date: 'Sponsor'},
        {text: '[কোম্পানি] — প্রপোজাল (Lead)', date: 'Sponsor'},
        {text: '[YYYY-MM-DD] — [কোম্পানি] মিটিং (Lead)', date: 'Sponsor'},
        {text: 'Seylon Tea (Lead)', date: 'Sponsor'},
        {text: 'মেঘনা (Lead)', date: 'Sponsor'},
        {text: 'Oppo (Lead)', date: 'Sponsor'},
        {text: 'Upay (Done)', date: 'Sponsor'},
        {text: 'ACI (Lead)', date: 'Sponsor'},
        {text: 'Diamond World (Lead)', date: 'Sponsor'},
        {text: 'FebriLife (Lead)', date: 'Sponsor'},
        {text: 'T.K Group (Lead)', date: 'Sponsor'},
        {text: 'Sambond (Lead)', date: 'Sponsor'},
      ]
    },
    finance: {
      title: 'Finance Portal',
      icon: '💰',
      desc: 'ধার/লোন + দৈনন্দিন খরচ ট্র্যাকিং',
      items: [
        {text: 'শিমুল — ৳100 (Paid)', date: 'Loan'},
        {text: 'নীল — ৳100 (Unpaid)', date: 'Loan'},
        {text: 'সেতু আপু — ৳2300 (Unpaid)', date: 'Loan'},
        {text: 'প্রিয়ন্তী — ৳1000 (Unpaid)', date: 'Loan'},
        {text: 'রুপন্তী — ৳790 (Unpaid)', date: 'Loan'},
        {text: 'জয় — ৳200 (Unpaid)', date: 'Loan'},
        {text: 'আজ কোনো খরচ রেকর্ড নাই', date: '2026-08-26'},
      ]
    },
    tasks: {
      title: "Today's Tasks",
      icon: '✅',
      desc: 'দৈনন্দিন To-Do ও পেন্ডিং কাজ',
      items: [
        {text: '[টাস্ক]', date: 'Pending'},
        {text: 'স্পন্সর ফলোআপ: IDLC (মঙ্গলবার কল)', date: '2026-08-25'},
      ]
    },
    google: {
      title: 'Google Workspace',
      icon: '🔗',
      desc: 'গুগল ক্যালেন্ডার, শিট, ডোক — রিমোট অ্যাক্সেস',
      items: [
        {text: '📅 Calendar (Upay mtg etc.)', date: 'google.com/calendar'},
        {text: '📊 Sponsor Sheet', date: 'docs.google.com/spreadsheets/d/1VxFfEIwhTtzl_SXjLr2gMjWLph_W-d9teGwy5fPx1cM/edit'},
        {text: '📝 Batch Day Notes Doc', date: 'docs.google.com/document/d/1i_mMMvhOgTfS3ImiEutB0vtrxbMybCQN5DKZsazlhAU/edit'},
      ]
    },
  }
};
